import Head from "next/head";
import Header from "../components/Header";
import Options from "../components/Options";
import Global from "../components/Global";
import Info from "../components/Info";
import Watch from "../components/Watch";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Traviling Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Options />
      <Global />
      <Info />
      <Watch />
      <Footer />
    </>
  );
}
